services:
  event-service-postgres:
    container_name: universe-simulator-event-service-postgres
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_DB=event-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - event-service-postgres:/var/lib/postgresql/data

volumes:
  event-service-postgres:
