services:
  event-service-mongo:
    container_name: universe-simulator-event-service-mongo
    image: mongo:6.0.1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - event-service-mongo:/data/db
volumes:
  event-service-mongo:
