services:
  vault:
    image: vault
    container_name: universe-simulator-vault
    restart: always
    cap_add:
      - IPC_LOCK
    command: server
    environment:
      - 'VAULT_LOCAL_CONFIG=
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/universe-simulator-cert.pem",
              "tls_key_file": "/vault/universe-simulator-key.pem"
            }
          },
          "ui": true
        }'
    ports:
      - 8200:8200
    volumes:
      - vault-logs:/vault/logs
      - vault-file:/vault/file
      - ~/universe-simulator/universe-simulator-cert.pem:/vault/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/vault/universe-simulator-key.pem

  zipkin:
    image: openzipkin/zipkin
    container_name: universe-simulator-zipkin
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5671
      - RABBIT_USER=username
      - RABBIT_PASSWORD=password
      - RABBIT_USE_SSL=true
    ports:
      - 9411:9411

  rabbitmq:
    image: rabbitmq:management
    container_name: universe-simulator-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SSL_CACERTFILE=/var/lib/rabbitmq/universe-simulator-cert.pem
      - RABBITMQ_SSL_CERTFILE=/var/lib/rabbitmq/universe-simulator-cert.pem
      - RABBITMQ_SSL_KEYFILE=/var/lib/rabbitmq/universe-simulator-key.pem
      - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false
    ports:
      - 5671:5671
      - 15671:15671
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ~/universe-simulator/universe-simulator-cert.pem:/var/lib/rabbitmq/universe-simulator-cert.pem
      - ~/universe-simulator/universe-simulator-key.pem:/var/lib/rabbitmq/universe-simulator-key.pem

volumes:
  vault-logs:
  vault-file:
  rabbitmq:
