= Project setup

== Software
Run `docker-compose -p universe-simulator up -d` to install all required software (`vault, rabbitmq,
mongo`).

== Https/TLS
You need to have a keystore file named `universe-simulator.p12` in your `${HOME}/universe-simulator`
directory. The certificate in the keystore can be either self-signed or provided by a CA.

=== Keystore
You can use java's `keytool` utility for working with keystore. To create a keystore file with a
self-signed certificate, run the following command: `keytool -genkeypair -alias universe-simulator
-keyalg RSA -validity 365 -keystore universe-simulator.p12` and follow the instructions.

== Vault
* When vault is up and running, go to vault ui at `localhost:8200` and follow the setup instructions.
* After the setup, log in and enable a new `KV` engine with `universe-simulator` as path. This root
path maps to the `spring.cloud.vault.kv.backend` property in `bootstrap.properties`.
* In the `universe-simulator` engine create a secret with `event-service/local` as path.
`event-service` maps to the `spring.application.name` property in `bootstrap.properties` and `local`
maps to your spring boot profile used for local development. Similarly, you can add as many
profile-specific paths as needed (e.g. `event-service/staging, event-service/prod`).
* Add all required properties from the `bootstrap.properties` file to the
`universe-simulator/event-service/local` path. You can identify such properties by the kebab-case
syntax (e.g. `${server-port}`).

== Environment variables
Add the following OS environment variables: `US_VAULT_HOST, US_VAULT_PORT, US_VAULT_TOKEN`. These are
needed for the vault connection.

== Properties file
Add `bootstrap-local.properties` file and if needed, override any properties from the
`bootstrap.properties` file.

== Running the application
You can run the application with the `local` profile from your IDE or with the following command:
`./gradlew bootRun --args='--spring.profiles.active=local'`.
