on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      checkout code
      - uses: actions/checkout@v2
#      install java
      - uses: actions/setup-java@v1
        with:
          java-version: 11
#      validate gradle wrapper    
      - uses: gradle/wrapper-validation-action@v1
#      build, test and code coverage  
      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build jacocoTestCoverageVerification --info --stacktrace
#      build docker image
      - uses: burrunan/gradle-cache-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          arguments: bootBuildImage --info --stacktrace
        env:
          US_DOCKER_REGISTRY_USER: ${{ secrets.US_DOCKER_REGISTRY_USER }}
          US_DOCKER_REGISTRY_PASSWORD: ${{ secrets.US_DOCKER_REGISTRY_PASSWORD }}
