on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - run: ./gradlew build jacocoTestReport jacocoTestCoverageVerification --build-cache --info --stacktrace
        env:
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      - run: ./gradlew sonarqube --build-cache --info --stacktrace
        env:
          US_SONARQUBE_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      - uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
      - name: publish
        if: github.ref == 'refs/heads/main'
        run: ./gradlew bootBuildImage --build-cache --info --stacktrace
        env:
          US_DOCKER_REGISTRY_USER: ${{ secrets.US_DOCKER_REGISTRY_USER }}
          US_DOCKER_REGISTRY_TOKEN: ${{ secrets.US_DOCKER_REGISTRY_TOKEN }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
