on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/wrapper-validation-action@v1
      - name: build, test & code coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jacocoTestReport jacocoTestCoverageVerification --build-cache --info --stacktrace --warning-mode all
        env:
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      - name: sonarqube
        uses: gradle/gradle-build-action@v2
        with:
          arguments: sonarqube --build-cache --info --stacktrace --warning-mode all
        env:
          US_SONARQUBE_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      - name: publish
        uses: gradle/gradle-build-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          arguments: bootBuildImage --build-cache --info --stacktrace --warning-mode all
        env:
          US_DOCKER_REGISTRY_USER: ${{ secrets.US_DOCKER_REGISTRY_USER }}
          US_DOCKER_REGISTRY_TOKEN: ${{ secrets.US_DOCKER_REGISTRY_TOKEN }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
