on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      # build, test & code coverage
      - uses: burrunan/gradle-cache-action@v1
        name: build, test & code coverage
        with:
          arguments: build jacocoTestReport jacocoTestCoverageVerification --info --stacktrace --warning-mode all
        env:
          US_GITHUB_PACKAGES_URL: ${{ secrets.US_GITHUB_PACKAGES_URL }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      # sonarqube
      - uses: burrunan/gradle-cache-action@v1
        name: sonarqube
        with:
          arguments: sonarqube --info --stacktrace --warning-mode all
        env:
          US_SONARQUBE_TOKEN: ${{ secrets.US_SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          US_GITHUB_PACKAGES_URL: ${{ secrets.US_GITHUB_PACKAGES_URL }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
      # publish
      - uses: burrunan/gradle-cache-action@v1
        name: publish
        if: github.ref == 'refs/heads/master'
        with:
          arguments: bootBuildImage --info --stacktrace --warning-mode all
        env:
          US_DOCKER_REGISTRY_USER: ${{ secrets.US_DOCKER_REGISTRY_USER }}
          US_DOCKER_REGISTRY_PASSWORD: ${{ secrets.US_DOCKER_REGISTRY_PASSWORD }}
          US_GITHUB_PACKAGES_URL: ${{ secrets.US_GITHUB_PACKAGES_URL }}
          US_GITHUB_PACKAGES_USER: ${{ secrets.US_GITHUB_PACKAGES_USER }}
          US_GITHUB_PACKAGES_TOKEN: ${{ secrets.US_GITHUB_PACKAGES_TOKEN }}
